# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/Spuit.Core" # Location of package manifests
    schedule:
      interval: "monthly"
      time: "01:00"
      timezone: "Asia/Tokyo"

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/Spuit.WPF" # Location of package manifests
    schedule:
      interval: "monthly"
      time: "01:00"
      timezone: "Asia/Tokyo"
